table DimDate
	lineageTag: 3f360fc5-5bb6-4470-94fc-750582b0b263

	column date_key
		dataType: int64
		lineageTag: 2339be2b-dd44-44fe-b029-29fcfb4a815e
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 5fef00e5-8c78-4c11-8622-040644780fb7
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: dfb47d5e-44db-4ed7-8508-a05a459c6c71
			defaultHierarchy: LocalDateTable_cffad7d5-8612-49c8-9c44-ab60318da3ff.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		lineageTag: d54a6321-4bbe-452c-a5c9-205bf6d41e8e
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		lineageTag: 6eaf20f8-3bcb-43a0-afae-095aa79078ef
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column quarter_name
		dataType: string
		lineageTag: a04e66eb-edcf-4fd7-b3b4-632b851bf055
		summarizeBy: none
		sourceColumn: quarter_name

		annotation SummarizationSetBy = Automatic

	column year_quarter
		dataType: string
		lineageTag: c4325a4f-102b-4615-8399-7029f39b3cb7
		summarizeBy: none
		sourceColumn: year_quarter

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		lineageTag: 573a34ed-f530-40a9-9d2d-dbb0f9d826c6
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 41f70bcf-9de1-4f40-a197-e8346a33c2b5
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: month

		annotation SummarizationSetBy = Automatic

	column month_short
		dataType: string
		lineageTag: a1117af4-81e8-4d45-b996-0528db2b9bfa
		summarizeBy: none
		sourceColumn: month_short
		sortByColumn: month

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: string
		lineageTag: 09bdbf2b-b639-495f-8e5e-090ed7a82c3f
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column day
		dataType: int64
		lineageTag: 133ef294-e8b1-45d2-b0ef-780f192b2b9f
		summarizeBy: sum
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column day_of_week
		dataType: int64
		lineageTag: f7ceee42-3969-4c4b-84b3-3aa9a9c8cacb
		summarizeBy: sum
		sourceColumn: day_of_week

		annotation SummarizationSetBy = Automatic

	column day_name
		dataType: string
		lineageTag: fdda95ab-24fb-42cd-ad63-1445076002ea
		summarizeBy: none
		sourceColumn: day_name

		annotation SummarizationSetBy = Automatic

	column week_of_year
		dataType: int64
		lineageTag: 85407a04-0052-4a33-be28-3f4be9ee1a94
		summarizeBy: sum
		sourceColumn: week_of_year

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		lineageTag: a8052d0e-eb19-4649-b8c9-acfb21afdb90
		summarizeBy: sum
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	partition DimDate = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Ecomercee\data\processed\\dim_date.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"date_key", Int64.Type}, {"date", type datetime}, {"year", Int64.Type}, {"quarter", Int64.Type}, {"quarter_name", type text}, {"year_quarter", type text}, {"month", Int64.Type}, {"month_name", type text}, {"month_short", type text}, {"year_month", type text}, {"day", Int64.Type}, {"day_of_week", Int64.Type}, {"day_name", type text}, {"week_of_year", Int64.Type}, {"is_weekend", Int64.Type}})
				in
				    #"Changed Type"

