table FactOrders
	lineageTag: 36bb492f-cb92-42fe-941c-0a335156150c

	measure 'Total Orders' = DISTINCTCOUNT(FactOrders[order_id])
		formatString: #,##0
		lineageTag: 61c91b94-adaa-4887-9088-23cee7f7b931

	measure 'Delivered Orders' = CALCULATE([Total Orders], FactOrders[order_status] = "delivered")
		formatString: #,##0
		lineageTag: b2c0cedf-119f-4dd5-9509-479841dfada3

	measure 'Cancelled Orders' = CALCULATE([Total Orders], FactOrders[order_status] = "canceled")
		formatString: #,##0
		lineageTag: 8a7d31c3-5298-42a2-9236-5171d0bf3d4c

	measure 'Delivery Rate' = DIVIDE([Delivered Orders], [Total Orders], 0)
		formatString: 0.00%
		lineageTag: 822a93e3-c23e-49d9-b97f-cd055c840f42

	measure 'Cancellation Rate' = DIVIDE([Cancelled Orders], [Total Orders], 0)
		formatString: 0.00%
		lineageTag: 6fd51d95-e9c2-46ce-871d-97cb910a3847

	measure 'Average Delivery Days' = CALCULATE(AVERAGE(FactOrders[delivery_days]), FactOrders[order_status] = "delivered")
		formatString: 0.00
		lineageTag: 2bec44d2-980a-45ce-9d3e-85c048696d2e

	measure 'Median Delivery Days' = CALCULATE(MEDIAN(FactOrders[delivery_days]), FactOrders[order_status] = "delivered")
		formatString: 0.00
		lineageTag: 866ebf14-7fca-43eb-93d3-41f9a5ffea95

	measure 'Delayed Orders' = CALCULATE([Total Orders], FactOrders[order_status] = "delivered", FactOrders[is_delayed] = 1)
		formatString: #,##0
		lineageTag: dc0e6647-5566-4898-a85d-a9bc1236071d

	measure 'Delay Rate' = DIVIDE([Delayed Orders], [Delivered Orders], 0)
		formatString: 0.00%
		lineageTag: da774cdc-0afb-43fa-a615-67c3ea6365d4

	column order_id
		dataType: string
		lineageTag: 7c25838c-6c62-41eb-a073-7b1a57cb6b39
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: 88514d05-a249-4db9-bee9-91ea842ea3f9
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column order_status
		dataType: string
		lineageTag: e39f4d65-d3c1-4774-858a-78ef890e08da
		summarizeBy: none
		sourceColumn: order_status

		annotation SummarizationSetBy = Automatic

	column order_purchase_timestamp
		dataType: dateTime
		formatString: yyyy-mm-dd hh:mm
		lineageTag: d8f62fc3-17a3-409d-b8d8-36b9bbf72b26
		summarizeBy: none
		sourceColumn: order_purchase_timestamp

		variation Variation
			isDefault
			relationship: 59485d04-333c-4ff4-8489-385bd1d30440
			defaultHierarchy: LocalDateTable_685a867f-8626-41e0-a0c4-20b233ad936f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column order_approved_at
		dataType: dateTime
		formatString: yyyy-mm-dd hh:mm
		lineageTag: fb972b55-98f2-4552-8687-e3f770297e5f
		summarizeBy: none
		sourceColumn: order_approved_at

		variation Variation
			isDefault
			relationship: 0aea5de1-46d9-40f5-9d1d-e3d3ce60cbfc
			defaultHierarchy: LocalDateTable_064b1870-7313-42eb-a82d-20c177fedd51.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column order_delivered_carrier_date
		dataType: dateTime
		formatString: yyyy-mm-dd hh:mm
		lineageTag: bd270752-d789-45e5-af05-6a7f8b5b676c
		summarizeBy: none
		sourceColumn: order_delivered_carrier_date

		variation Variation
			isDefault
			relationship: 5176b06f-fc16-4e4b-b4e3-8bebcffd2c3c
			defaultHierarchy: LocalDateTable_0b2583f1-1e73-45ba-a11a-e01608ab35f6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column order_delivered_customer_date
		dataType: dateTime
		formatString: yyyy-mm-dd hh:mm
		lineageTag: aec722ca-128a-4760-aa4a-6482d5a36850
		summarizeBy: none
		sourceColumn: order_delivered_customer_date

		variation Variation
			isDefault
			relationship: 0088f5fc-9705-4cf8-a490-99a260dcc673
			defaultHierarchy: LocalDateTable_96308617-f40d-4a7b-b9ce-aba367be8b0b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column order_estimated_delivery_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 56e4f377-8d7f-4ade-ad5b-d77f56b39192
		summarizeBy: none
		sourceColumn: order_estimated_delivery_date

		variation Variation
			isDefault
			relationship: 04c37761-fc84-41e2-9f2f-de96ccafb615
			defaultHierarchy: LocalDateTable_e01a74a2-51a6-478b-b85e-f6193082d2f5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column order_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: c89bd956-c80a-4e12-ae0b-001863af1e06
		summarizeBy: none
		sourceColumn: order_date

		annotation SummarizationSetBy = Automatic

	column order_year
		dataType: int64
		lineageTag: f2421934-faad-47da-aaca-d955eee13e5c
		summarizeBy: sum
		sourceColumn: order_year

		annotation SummarizationSetBy = Automatic

	column order_month
		dataType: int64
		lineageTag: 4e769338-49cc-4516-a83d-bba253964e0d
		summarizeBy: sum
		sourceColumn: order_month

		annotation SummarizationSetBy = Automatic

	column order_month_name
		dataType: string
		lineageTag: 8512a93b-a1b5-45ba-9bdc-37eff29b4666
		summarizeBy: none
		sourceColumn: order_month_name

		annotation SummarizationSetBy = Automatic

	column order_year_month
		dataType: string
		lineageTag: 0c7b21ca-99fc-46a2-8fa9-d31a88c4916e
		summarizeBy: none
		sourceColumn: order_year_month

		annotation SummarizationSetBy = Automatic

	column order_quarter
		dataType: int64
		lineageTag: 519a50e0-7e00-40c4-a08c-7c4f0dbb1d43
		summarizeBy: sum
		sourceColumn: order_quarter

		annotation SummarizationSetBy = Automatic

	column order_day_of_week
		dataType: string
		lineageTag: f0431885-a8d0-4b29-a186-2e737c766610
		summarizeBy: none
		sourceColumn: order_day_of_week

		annotation SummarizationSetBy = Automatic

	column delivery_days
		dataType: double
		formatString: 0.00
		lineageTag: 044a6eb3-ad7f-48fe-b566-be699b667854
		summarizeBy: sum
		sourceColumn: delivery_days

		annotation SummarizationSetBy = Automatic

	column approval_days
		dataType: double
		formatString: 0.00
		lineageTag: 44ea01cc-a12e-42fd-a14e-67bdb80801a2
		summarizeBy: sum
		sourceColumn: approval_days

		annotation SummarizationSetBy = Automatic

	column estimated_delivery_gap
		dataType: double
		formatString: 0.00
		lineageTag: 23ec5223-5e57-4c43-9bc6-8d65baa712f1
		summarizeBy: sum
		sourceColumn: estimated_delivery_gap

		annotation SummarizationSetBy = Automatic

	column is_delayed
		dataType: int64
		lineageTag: 6b2c1f2f-9680-43f1-85f8-0dbc91f0b619
		summarizeBy: sum
		sourceColumn: is_delayed

		annotation SummarizationSetBy = Automatic

	column customer_unique_id
		dataType: string
		lineageTag: d3ef7bf9-eb63-4e9c-8b43-8a3daaebae4b
		summarizeBy: none
		sourceColumn: customer_unique_id

		annotation SummarizationSetBy = Automatic

	column customer_city
		dataType: string
		lineageTag: 0abca40a-3d5b-4746-b788-4918b2815535
		summarizeBy: none
		sourceColumn: customer_city

		annotation SummarizationSetBy = Automatic

	column customer_state
		dataType: string
		lineageTag: 9465d90d-ad54-41f5-a66d-c09ed3fa72e5
		summarizeBy: none
		sourceColumn: customer_state

		annotation SummarizationSetBy = Automatic

	column customer_order_count
		dataType: int64
		lineageTag: e969c519-8eff-4472-8637-a746e2a1fed6
		summarizeBy: sum
		sourceColumn: customer_order_count

		annotation SummarizationSetBy = Automatic

	column customer_total_spend
		dataType: double
		formatString: R$ #,##0.00
		lineageTag: eb6f1513-00b7-479b-bf9a-c459b0bd9bce
		summarizeBy: sum
		sourceColumn: customer_total_spend

		annotation SummarizationSetBy = Automatic

	column customer_value_segment
		dataType: string
		lineageTag: e546f786-6cce-4652-bbcc-5951727804df
		summarizeBy: none
		sourceColumn: customer_value_segment

		annotation SummarizationSetBy = Automatic

	column customer_type
		dataType: string
		lineageTag: 2ee7972d-2ab3-4e61-bf68-7dc331bdaf78
		summarizeBy: none
		sourceColumn: customer_type

		annotation SummarizationSetBy = Automatic

	partition FactOrders = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Ecomercee\data\processed\\fact_orders_clean.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"order_id", type text}, {"customer_id", type text}, {"order_status", type text}, {"order_purchase_timestamp", type datetime}, {"order_approved_at", type datetime}, {"order_delivered_carrier_date", type datetime}, {"order_delivered_customer_date", type datetime}, {"order_estimated_delivery_date", type datetime}, {"order_date", type datetime}, {"order_year", Int64.Type}, {"order_month", Int64.Type}, {"order_month_name", type text}, {"order_year_month", type text}, {"order_quarter", Int64.Type}, {"order_day_of_week", type text}, {"delivery_days", type number}, {"approval_days", type number}, {"estimated_delivery_gap", type number}, {"is_delayed", Int64.Type}, {"customer_unique_id", type text}, {"customer_city", type text}, {"customer_state", type text}, {"customer_order_count", Int64.Type}, {"customer_total_spend", type number}, {"customer_value_segment", type text}, {"customer_type", type text}})
				in
				    #"Changed Type"

